m=input ("Digite um nome",).strip ()
print ("Analisando seu nome...")
print (f"Seu nome tudo em maiúsculas fica ", m.upper() )
print (f" seu nome todo em minúsculas fica ",m.lower())
print (f" Seu nome tem ",len(m)-m.count (' '))
print (f"O seu primeiro nome é",m.split () [0])
